# prometheus/prometheus.yml
global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "flask-app"
    static_configs:
      - targets: ["flask-app:5500"]
    metrics_path: "/metrics"

  - job_name: "gin-app"
    static_configs:
      - targets: ["demo-go:8090"]
    metrics_path: "/metrics"
